/**
 * api.ts — TypeScript Type Definitions for Admin Dashboard API
 *
 * Autogenerated from Prisma schema + API endpoint analysis.
 * Zero implementation, only type definitions.
 */

// ============================================================================
// AUTH & USER TYPES
// ============================================================================

/** Login method enum — how users authenticate */
export type LoginMethod = "email" | "github" | "linkedin" | "google";

/** User role — determines API access permissions */
export type UserRole = "user" | "company" | "admin";

/** Core user entity from database */
export interface User {
  id: string;
  email: string;
  password?: string | null; // nullable for OAuth users
  first_name: string;
  last_name: string;
  role: UserRole;
  oauth_provider?: "github" | "linkedin" | "google" | null;
  oauth_id?: string | null;
  phone?: string | null;
  location?: string | null;
  bio?: string | null;
  birthDate?: string | null;
  avatar?: string | null;
  created_at?: Date | string | null;
  updated_at?: Date | string;
}

/** User profile — extended user data (skills, languages, etc) */
export interface UserProfile {
  id: string;
  user_id: string;
  languages: string[];
  skills: string[];
  seniority?: string | null;
  availability?: string | null;
  workModes: string[];
  cv_url?: string | null;
  bio?: string | null;
  location?: string | null;
  location_geo?: LocationGeo | null;
  github?: string | null;
  linkedin?: string | null;
  website?: string | null;
  created_at?: Date | string | null;
  updated_at?: Date | string;
}

/** Auth response from login/register endpoints */
export interface AuthResponse {
  success: boolean;
  status: number;
  message: string;
  data: {
    user: User;
    token: string;
    refreshToken: string;
  };
}

// ============================================================================
// GEO & LOCATION TYPES
// ============================================================================

/** GeoJSON Point format — used in location_geo fields */
export interface LocationGeo {
  type: "Point";
  coordinates: [number, number]; // [longitude, latitude]
}

// ============================================================================
// JOB TYPES
// ============================================================================

/** Job employment type */
export type EmploymentType =
  | "FULL_TIME"
  | "PART_TIME"
  | "CONTRACT"
  | "FREELANCE"
  | "TEMPORARY";

/** Job experience level */
export type ExperienceLevel = "JUNIOR" | "MIDDLE" | "SENIOR" | "LEAD";

/** Job contract type */
export type ContractType = "PERMANENT" | "TEMPORARY" | "PROJECT" | "FREELANCE";

/** Job status */
export type JobStatus = "active" | "expired" | "draft" | "closed";

/** Core job entity */
export interface Job {
  id: string;
  company_id?: string | null;
  seniority_id?: string | null;
  title: string;
  description: string;
  link?: string | null;
  source?: string | null; // e.g., "linkedin", "indeed"
  original_language?: string | null;
  language?: string | null;
  published_at?: Date | string | null;

  requirements: string[];
  benefits: string[];
  salary_min?: number | null;
  salary_max?: number | null;

  location?: string | null;
  remote: boolean;
  is_remote?: boolean | null;
  formatted_address?: string | null;
  city?: string | null;
  country?: string | null;
  location_geo?: LocationGeo | null;
  formatted_address_verified?: string | null;
  location_raw?: string | null;

  employment_type?: string | null;
  experience_level?: string | null;
  seniority?: string | null;

  skills: string[];
  technical_skills?: string[] | null;

  views_count: number;
  clicks_count: number;
  status: JobStatus;
  created_at?: Date | string | null;
  updated_at?: Date | string;
  expires_at?: Date | string | null;

  // Relation (optional in response)
  company?: Company | null;
}

// ============================================================================
// COMPANY TYPES
// ============================================================================

/** Company entity */
export interface Company {
  id: string;
  name: string;
  description?: string | null;
  website?: string | null;
  industry?: string | null;
  size?: string | null; // e.g., "1-10", "10-50", "50-200", "200+"
  location?: string | null;
  logo?: string | null;
  logo_url?: string | null;
  trustScore: number; // 0-100
  totalRatings: number;
  totalLikes: number;
  totalDislikes: number;
  created_at?: Date | string | null;
  updated_at?: Date | string;

  // Relations (optional)
  jobs?: Job[] | null;
}

// ============================================================================
// NEWS TYPES
// ============================================================================

/** News translation object */
export interface NewsTranslation {
  language: string; // "it", "en", "es", "de", "fr"
  title: string;
  summary?: string | null;
  content?: string | null;
}

/** News entity */
export interface News {
  id: string;
  title: string;
  slug: string;
  summary?: string | null;
  content?: string | null;
  source_url?: string | null;
  image_url?: string | null;
  category?: string | null; // e.g., "AI", "IT", "Security"
  language?: string | null;
  translations: NewsTranslation[];
  is_published: boolean;
  published_at?: Date | string | null;
  views_count: number;
  clicks_count: number;
  created_at?: Date | string | null;
  updated_at?: Date | string;
}

// ============================================================================
// COMMENT & INTERACTION TYPES
// ============================================================================

/** Comment entity — supports nested replies */
export interface Comment {
  id: string;
  commentable_id: string;
  commentable_type: "job" | "news";
  user_id: string;
  content: string;
  parentId?: string | null;
  created_at?: Date | string | null;
  updated_at?: Date | string;

  // Relations
  user?: User | null;
  parent?: Comment | null;
  replies?: Comment[] | null;
}

/** Like/Dislike interaction */
export interface Like {
  id: string;
  user_id: string;
  likeable_type: "job" | "news" | "comment";
  likeable_id: string;
  type: "LIKE" | "DISLIKE";
  created_at?: Date | string | null;

  user?: User | null;
}

/** Interaction type — tracks views, clicks, applications */
export type InteractionType = "VIEW" | "CLICK" | "APPLY";

/** Interaction entity — analytics tracking */
export interface Interaction {
  id: string;
  trackable_id: string;
  trackable_type: "job" | "news";
  user_id?: string | null;
  fingerprint?: string | null; // device fingerprint for anonymous tracking
  type: InteractionType;
  created_at?: Date | string | null;

  user?: User | null;
}

// ============================================================================
// FAVORITE TYPES
// ============================================================================

/** Favorite job saved by user */
export interface Favorite {
  id: string;
  user_id: string;
  job_id: string;
  created_at?: Date | string | null;

  user?: User | null;
  job?: Job | null;
}

// ============================================================================
// RESPONSE TYPES
// ============================================================================

/** Paginated response wrapper */
export interface PaginatedResponse<T> {
  success: boolean;
  status: number;
  message: string;
  data: {
    data: T[];
    total: number;
    page: number;
    limit: number;
    totalPages: number;
  };
}

/** Standard error response */
export interface ApiError {
  success: false;
  status: number;
  message: string;
  errors?: Record<string, string[]>;
}

// ============================================================================
// ANALYTICS TYPES
// ============================================================================

/** Timeline data point — for charts and graphs */
export interface TimelinePoint {
  date?: string; // ISO 8601 date
  week?: string; // e.g., "2026-W07"
  count: number;
}

/** Admin overview statistics */
export interface AdminStats {
  success: boolean;
  data: {
    users: number;
    jobs: number;
    companies: number;
    news: number;
    usersChange: number; // % change vs previous period
    jobsChange: number;
    companiesChange?: number;
    newsChange?: number;
  };
}

/** Distribution of login methods */
export interface LoginMethodDist {
  method: LoginMethod;
  count: number;
}

/** Top skill data */
export interface TopSkill {
  skill: string;
  count: number;
}

/** Top language data */
export interface Language {
  language: string;
  count: number;
}

/** Search log query data */
export interface SearchLog {
  keyword: string;
  count: number;
  viewsPerQuery?: number;
  appliesPerQuery?: number;
}

/** Registration statistics by time period */
export interface RegistrationStat {
  period: string; // date or week identifier
  count: number;
  trend?: number; // % change vs previous period
}

// ============================================================================
// FILTER & QUERY TYPES
// ============================================================================

/** Jobs list filter parameters */
export interface JobsFilterParams {
  page?: number;
  limit?: number;
  search?: string;
  skills?: string[];
  type?: EmploymentType;
  contractType?: ContractType;
  level?: ExperienceLevel;
  language?: string;
  company?: string;
  remote?: boolean;
  status?: JobStatus;
  dateFrom?: string; // ISO 8601
  dateTo?: string;
}

/** Companies list filter parameters */
export interface CompaniesFilterParams {
  page?: number;
  limit?: number;
  search?: string;
  industry?: string;
  verified?: boolean;
}

/** News list filter parameters */
export interface NewsFilterParams {
  page?: number;
  limit?: number;
  search?: string;
  category?: string;
  language?: string;
  dateFrom?: string;
  dateTo?: string;
}

// ============================================================================
// SKILL & METADATA TYPES
// ============================================================================

/** Skill aggregate data */
export interface SkillAggregate {
  skill: string;
  count: number;
  jobs: number;
  avgSalaryMin?: number;
  avgSalaryMax?: number;
}

/** Seniority level */
export interface Seniority {
  id: string;
  level: string;
  created_at?: Date | string | null;
}

// ============================================================================
// SERVICE RESPONSE TYPES
// ============================================================================

/** Generic create/update response */
export interface CreateResponse<T> {
  success: boolean;
  status: number;
  message: string;
  data: T;
}

/** Generic delete response */
export interface DeleteResponse {
  success: boolean;
  status: number;
  message: string;
}

// ============================================================================
// ADMIN-SPECIFIC TYPES
// ============================================================================

/** Admin permissions based on role */
export interface AdminPermissions {
  canManageUsers: boolean;
  canManageJobs: boolean;
  canManageCompanies: boolean;
  canManageNews: boolean;
  canViewAnalytics: boolean;
  canManageAdmins: boolean;
}

/** Admin dashboard context */
export interface AdminDashboardContext {
  user: User;
  permissions: AdminPermissions;
  filterPeriod?: "week" | "month" | "quarter" | "year" | "custom";
  dateRangeStart?: string;
  dateRangeEnd?: string;
}
